version: '2'
services:
  mqtt:
    image: ansi/raspberrypi3-mosquitto
    container_name: msgflo-project-mosquitto
    ports:
      - '127.0.0.1:1883:1883'
    entrypoint: /usr/local/sbin/mosquitto
  msgflo:
    image: msgflo/raspberrypi3-msgflo-project
    build:
      context: .
      dockerfile: Dockerfile-raspberrypi3
    container_name: msgflo-project
    environment:
      MSGFLO_BROKER: 'mqtt://mqtt:1883'
    ports:
      - '127.0.0.1:3569:3569'
    links:
      - mqtt
