#!/bin/bash
# Start the components needed by msgflo, then start the package including the specified graph

# Derek Knight
# Jun 2019

debug_flag='false'
graph_file="graphs/main.json"
verbose='false'
print_usage() {
  echo "Usage: '$0' -d -g <graph file>"
  echo " Parameters"
  echo "  -d              - Turn on debugging (default off)"
  echo "  -g <graph file> - Specify the graph file to use (default graphs\main.json)"
}

while getopts 'dg:v' flag; do
  case "${flag}" in
    d) debug_flag='true' ;;
    g) graph_file="${OPTARG}" ;;
    v) verbose='true' ;;
    *) print_usage
       exit 1 ;;
  esac
done

if [ ! -f "${graph_file}" ]; then
  echo "Graph file '${graph_file}' not found"
  exit 2
fi

export MSGFLO_BROKER="mqtt://pub_client:password@192.168.0.148"
if [ ${debug_flag} == 'true' ]; then
  export DEBUG="*"
fi
export GRAPH="tmp/main.json"

rm -f ./tmp/debug.log
cp ${graph_file} ./tmp/main.json

./node_modules/.bin/msgflo-nodejs --name msgflo-components/Repeat_1n6a3 components/Repeat.coffee 2>> ./tmp/debug.log &
./node_modules/.bin/msgflo-nodejs --name msgflo-components/Reverse_hlhnz components/Reverse.coffee 2>> ./tmp/debug.log &
./node_modules/.bin/msgflo-nodejs --name msgflo-components/Add_hrfxc components/Add.coffee 2>> ./tmp/debug.log &
./node_modules/.bin/msgflo-nodejs --name msgflo-components/Append_p0e67 components/Append.coffee 2>> ./tmp/debug.log &

npm start 2>> ./tmp/debug.log
